### ISSUE TITLE
License List updated to version 3.0

### ISSUE THREAD

**Issue by peti** [phadej/spdx#10]
Just a quick heads-up: The SPDX license list https://spdx.org/licenses/ was updated to version 3.0 and I understand that there were a couple of surprising changes with regard to GPL etc. It would be nice to see those modifications reflected in this library.

**Comment by phadej** [comment]
@peti thanks for heads up. I updated the `Cabal-2.2` branch with spdx-3.0 info. I'm not sure what to do with `spdx` package.

My plan was to make it a shim for `Cabal` (i.e. define the same types as in `Cabal` if `Cabal` is old) and build further functionality on top. How does this sound?

**Comment by peti** [comment]
> My plan was to make it a shim for Cabal (i.e. define the same types as in Cabal if Cabal is old) and build further functionality on top. How does this sound?

Yes, that sounds like a very good idea. I was hoping to switch my code to Cabal 2.2.x as soon as it comes out anyway.

**Comment by phadej** [comment]
Released https://hackage.haskell.org/package/spdx-1
