### ISSUE TITLE
Release current master to Hackage so we can build against 8.4.2

### ISSUE THREAD

**Issue by kritzcreek** [phadej/spdx#12]
I pointed stack against the master of this repo in https://github.com/purescript/purescript/pull/3372 and everything builds and runs fine, so I'd appreciate a release to hackage, Thanks!

**Comment by kritzcreek** [comment]
Ping, anything I can do to help make this happen?

**Comment by chisui** [comment]
This breaks `purescript` on NixOs.

**Comment by felixmulder** [comment]
This is affecting us as well since spdx requires `base < 4.11` and as such cannot be built on NIx.

Please let us know if we can help make this happen.

**Comment by kritzcreek** [comment]
@chisui This libraries development won't be continued. We've since made the switch to the Cabal library inside PureScript. Can NixOS work off of the unreleased master of the PureScript compiler? Such an inward facing change isn't really suited for triggering a compiler release.

**Comment by phadej** [comment]
I never said development won't be continued.

**Comment by kritzcreek** [comment]
Oh sorry, then I misunderstood that, so should I leave this issue around?

**Comment by phadej** [comment]
To be clear: I won't release `spdx` in its current form, as one can/should use `Cabal` - only when the stuff in `Cabal` is not enough, I'll have enough motivation to do something to `spdx`.

So this issue can stay closed.
