### ISSUE TITLE
Build failure on GHC 7.4 due to GHC.Generics

### ISSUE THREAD

**Issue by bergmark** [phadej/spdx#2]
before GHC 7.6 GHC.Generics lived in `ghc-prim`. If you want backwards compatibility you can (conditionally) add `ghc-prim` as a build-dependency, otherwise put a `base >= 4.6` lower bound.

**Comment by bergmark** [comment]
I revised the current versions (http://hackage.haskell.org/package/spdx-0.1.0.0/revisions/) so a new release is only needed if you want to add GHC<7.6 support.

**Comment by phadej** [comment]
Thanks for the report. It was easy to add GHC 7.4 support, so I did it.
