### ISSUE TITLE
Maybe create a new release?

### ISSUE THREAD

**Issue by maxhbr** [phadej/spdx#28]
using this package in version 1.0.0.2 has issues in combination with LTS Haskell 19.6. A new release containing e.g. the changes
https://github.com/phadej/spdx/blob/ef1807e08299150e4b42dfb33e87e2982be8d49c/spdx.cabal#L53
would help

**Comment by phadej** [comment]
https://hackage.haskell.org/package/spdx-1.0.0.3 published

**Comment by maxhbr** [comment]
Thank you!
