### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ncfavier** [phadej/spdx#33]
Please

**Comment by csasarak** [comment]
I would also like a new hackage release. If there's anything I can do to assist I'd like to contribute.

**Comment by Vekhir** [comment]
@phadej Can you make a new release for `spdx` to enable Arch to update easily to the newer `GHC` versions? Especially since `GHC 9.4` support requires code changes.
-- Vekhir

**Comment by phadej** [comment]
https://hackage.haskell.org/package/spdx-1.1
