### ISSUE TITLE
Too strict lower bounds on test dependencies

### ISSUE THREAD

**Issue by sternenseemann** [phadej/spdx#62]
```
tasty >=1.5 && <1.6, tasty-quickcheck >=0.11 && <0.12
```

tasty 1.4 and tasty-quickcheck 0.10 (from Stackage LTS 22) work fine according to my testing.

**Comment by phadej** [comment]
tasty-1.5 is almost a year old release, sorry I wont bother.

EDIT: In particular I don't bother to make my packages work with Stackage snapshots, even nightly is too slow to include new package versions, which are sometimes long awaited even before additional delays.
